Pair agent
elementary/switchboard-plug-bluetooth pull request #143
Opened 2020-09-24 01:36 UTC by torikulhabib

Please correct it if there is something wrong.
I try to match the example and doc bluez as needed.
https://github.com/elementary/switchboard-plug-bluetooth/issues/30

2021-02-15 17:40 UTC, jeremypw commented on src/DeviceRow.vala
> +                device.trusted = device.paired; //paired an trusted
`//paired and trusted`

2021-02-15 17:46 UTC, jeremypw commented on src/PairDialog.vala
> +                var entry_pin = new Gtk.Entry ();
Current recommended code style is to set properties on creation:
```
var entry_pin = new Gtk.Entry () {
    activates_default = true,
    xalign = 0.5f,
    ...
    width_chars = 16
};
```

2021-02-15 17:48 UTC, jeremypw commented on src/PairDialog.vala
> +                var entry_passkey = new Gtk.Entry ();
Set properties on creation (see above)

2021-02-15 17:50 UTC, jeremypw commented on src/PairDialog.vala
> +            device.blocked = false; // remove bloking
`// remove blocking`

2021-02-15 17:51 UTC, jeremypw commented on src/PairDialog.vala
> +    public uint32 get_paskey () {
Should be `get_passkey ()`?

2021-02-18 23:15 UTC, torikulhabib reviewed
I've changed it.

2021-03-02 10:31 UTC, davidmhewitt requested changes

2021-03-02 10:31 UTC, davidmhewitt commented on src/DeviceRow.vala
> +        // changed because to avoid :warning: Access to possible `null'. Perform a check or use an unsafe cast.:
```suggestion
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/DeviceRow.vala
> +        // changed because to avoid :warning: Access to possible `null'. Perform a check or use an unsafe cast.:
```suggestion
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +    public uint32 passkey_uint32 { get; construct; }
```suggestion
    public string pincodes { get; private set; }
    public uint32 passkey_uint32 { get; private set; }
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +        REQUESTPASSKEY,
```suggestion
        REQUEST_PIN,
        REQUEST_PASSKEY,
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +            auth_type: AuthType.REQUESTPIN,
```suggestion
            auth_type: AuthType.REQUEST_PIN,
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +            auth_type: AuthType.REQUESTPASSKEY,
```suggestion
            auth_type: AuthType.REQUEST_PASSKEY,
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +            case AuthType.REQUESTPIN:
```suggestion
            case AuthType.REQUEST_PIN:
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +                secondary_text = _("Make sure the PIN on “%s” and the one you enter the PIN code below match.").printf (device_name);
```suggestion
                secondary_text = _("Enter the pin displayed on “%s”").printf (device_name);
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +                entry_pin.changed.connect (()=>{
```suggestion
                entry_pin.changed.connect (() => {
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +            case AuthType.REQUESTPASSKEY:
```suggestion
            case AuthType.REQUEST_PASSKEY:
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +                secondary_text = _("Make sure the Passkey on “%s” and the one you enter the Passkey code below match.").printf (device_name);
```suggestion
                secondary_text = _("Enter the passkey displayed on “%s”").printf (device_name);
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +                entry_passkey.changed.connect (()=>{
```suggestion
                entry_passkey.changed.connect (() => {
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +        destroy.connect (()=>{
```suggestion
        destroy.connect (() => {
```

2021-03-02 10:31 UTC, davidmhewitt commented on src/PairDialog.vala
> +    public uint32 get_upasskey () {
```suggestion
    }
    
    public uint32 get_upasskey () {
```

2021-03-02 11:16 UTC, davidmhewitt requested changes

2021-03-02 11:16 UTC, davidmhewitt commented on src/PairDialog.vala
> +    public string pincodes { get; private set; }
```suggestion
    public string pincode { get; private set; }
```

2021-03-02 11:16 UTC, davidmhewitt commented on src/PairDialog.vala
> +                    pincodes = entry_pin.text;
```suggestion
                    pincode = entry_pin.text;
```

2021-03-02 11:16 UTC, davidmhewitt commented on src/PairDialog.vala
> +    }
```suggestion
```

2021-03-02 11:16 UTC, davidmhewitt commented on src/Services/Agent.vala
> +        return pair_dialog.get_pincode ();
```suggestion
        return pair_dialog.pincode;
```

2021-03-02 11:16 UTC, davidmhewitt commented on src/PairDialog.vala
> +                    passkey_uint32 = (uint32) uint64.parse (entry_passkey.text);
```suggestion
                    passkey_uint32 = uint.parse (entry_passkey.text);
```

2021-03-02 11:17 UTC, davidmhewitt commented on src/Services/Agent.vala
> +        return pair_dialog.get_upasskey ();
```suggestion
        return pair_dialog.passkey_uint32;
```

2021-03-11 17:36 UTC, jeremypw reviewed
Needs conflicts fixing.
Could successfully pair and connect with Android phone entering a passcode but the same dialog appeared whether or not the pairing was initiated from elementary or the phone (that is, the "request" dialog and not the "display" dialog.  Is this correct?

Still paired connected OK with headphones not requiring authentication.

Will check behaviour against Ubuntu.  Needs testing by others with different device authentication modes.

2023-03-11 14:56 UTC, closed without merging